package thedimas.network.enums;

public enum ServerAction {
    HOST, STOP, EXIT, RESTART, STATUS,
    JS, COMMAND, SAY,
    BAN, UNBAN, ADMIN, UNADMIN, KICK, PARDON,
    PLAYERS, UNITS, MAPS, GET_MAP, KICKS,
    IPS_BLACKLISTED, CLEAR_BLACKLIST, UNBLACKLIST,
    GAME_OVER, SKIP_WAVE, NEXT_MAP
}
